#!/usr/bin/env bash 


new_terminal() {
    if [ "$(uname)" == "Darwin" ]; then
        ngrok-qr-generator-osascript "$@"    
    elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
        gnome-terminal -e "ngrok-qr-generator \"$a\" ";
    else
        echo "Unsupported OS"
        exit
    fi
}


new_terminal "$@" && ngrok "$@"
